edition = "2024"
version = "Two"
newline_style = "unix"
use_field_init_shorthand = true
use_try_shorthand = true
unstable_features = true
max_width = 150
comment_width = 150
wrap_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
error_on_line_overflow = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Module"
tab_spaces = 4
reorder_modules = false
merge_derives = false
use_small_heuristics = "Max"
# group_imports = "StdExternalCrate"
